package jooon.features.fishing

public object FishingStrings {
   public final val seaCreatureMessages: Map<String, String> =
      MapsKt.mapOf(
         arrayOf(
            TuplesKt.to("A Squid appeared.", "Squid"),
            TuplesKt.to("You caught a Sea Walker.", "Sea Walker"),
            TuplesKt.to("You stumbled upon a Sea Guardian.", "Sea Guardian"),
            TuplesKt.to("It looks like you've disrupted the Sea Witch's brewing session. Watch out, she's furious!", "Sea Witch"),
            TuplesKt.to("You reeled in a Sea Archer.", "Sea Archer"),
            TuplesKt.to("The Rider of the Deep has emerged.", "Rider Of The Deep"),
            TuplesKt.to("Huh? A Catfish!", "Catfish"),
            TuplesKt.to("Is this even a fish? It's the Carrot King!", "Carrot King"),
            TuplesKt.to("Gross! A Sea Leech!", "Sea Leech"),
            TuplesKt.to("You've discovered a Guardian Defender of the sea.", "Guardian Defender"),
            TuplesKt.to("You have awoken the Deep Sea Protector, prepare for a battle!", "Deep Sea Protector"),
            TuplesKt.to("The Water Hydra has come to test your strength.", "Water Hydra"),
            TuplesKt.to("The Sea Emperor arises from the depths.", "Sea Emperor"),
            TuplesKt.to("Phew! It's only a Scarecrow.", "Scarecrow"),
            TuplesKt.to("You hear trotting from beneath the waves, you caught a Nightmare.", "Nightmare"),
            TuplesKt.to("It must be a full moon, a Werewolf appears.", "Werewolf"),
            TuplesKt.to("The spirit of a long lost Phantom Fisher has come to haunt you.", "Phantom Fisher"),
            TuplesKt.to("This can't be! The manifestation of death himself!", "Grim Reaper"),
            TuplesKt.to("Frozen Steve fell into the pond long ago, never to resurface...until now!", "Frozen Steve"),
            TuplesKt.to("It's a snowman! He looks harmless", "Frosty The Snowman"),
            TuplesKt.to("The Grinch stole Jerry's Gifts...get them back!", "Grinch"),
            TuplesKt.to("What is this creature!?", "Yeti"),
            TuplesKt.to("You found a forgotten Nutcracker laying beneath the ice.", "Nutcracker"),
            TuplesKt.to("A Reindrake forms from the depths.", "Reindrake"),
            TuplesKt.to("A tiny fin emerges from the water, you've caught a Nurse Shark.", "Nurse Shark"),
            TuplesKt.to("You spot a fin as blue as the water it came from, it's a Blue Shark.", "Blue Shark"),
            TuplesKt.to("A striped beast bounds from the depths, the wild Tiger Shark!", "Tiger Shark"),
            TuplesKt.to("Hide no longer, a Great White Shark has tracked your scent and thirsts for your blood!", "Great White Shark"),
            TuplesKt.to("From beneath the lava appears a Magma Slug.", "Magma Slug"),
            TuplesKt.to("You hear a faint Moo from the lava... A Moogma appears.", "Moogma"),
            TuplesKt.to("A small but fearsome Lava Leech emerges.", "Lava Leech"),
            TuplesKt.to("You feel the heat radiating as a Pyroclastic Worm surfaces.", "Pyroclastic Worm"),
            TuplesKt.to("A Lava Flame flies out from beneath the lava.", "Lava Flame"),
            TuplesKt.to("A Fire Eel slithers out from the depths.", "Fire Eel"),
            TuplesKt.to("Taurus and his steed emerge.", "Taurus"),
            TuplesKt.to("You hear a massive rumble as Thunder emerges.", "Thunder"),
            TuplesKt.to("You have angered a legendary creature... Lord Jawbus has arrived", "Lord Jawbus"),
            TuplesKt.to("A Water Worm surfaces!", "Water Worm"),
            TuplesKt.to("A Poisoned Water Worm surfaces!", "Poisoned Water Worm"),
            TuplesKt.to("A Zombie miner surfaces!", "Zombie Miner"),
            TuplesKt.to("A flaming worm surfaces from the depths!", "Flaming Worm"),
            TuplesKt.to("A Lava Blaze has surfaced from the depths!", "Lava Blaze"),
            TuplesKt.to("A Lava Pigman arose from the depths!", "Lava Pigman"),
            TuplesKt.to("Your Chumcap Bucket trembles, it's an Agarimoo.", "Agarimoo"),
            TuplesKt.to("An Oasis Rabbit appears from the water.", "Oasis Rabbit"),
            TuplesKt.to("An Oasis Sheep appears from the water.", "Oasis Sheep"),
            TuplesKt.to("An Abyssal Miner breaks out of the water!", "Abyssal Miner"),
            TuplesKt.to("The desolate wail of a Banshee breaks the silence.", "Banshee"),
            TuplesKt.to("A swampy mass of slime emerges, the Bayou Sludge!", "Bayou Sludge"),
            TuplesKt.to("A garish set of tentacles arise. It's a Blue Ringed Octopus!", "Blue Ringed Octopus"),
            TuplesKt.to("Emerging from the depths, the Dumpster Diver scavenges for treasures.", "Dumpster Diver"),
            TuplesKt.to("A swampy mass of slime emerges, the Dumpster Diver!", "Dumpster Diver"),
            TuplesKt.to("A Dumpster Diver has emerged from the swamp!", "Dumpster Diver"),
            TuplesKt.to("Leaping into action, the Frog Man croaks a battle cry.", "Frog Man"),
            TuplesKt.to("With a powerful snap, the Snapping Turtle challenges its foes.", "Snapping Turtle"),
            TuplesKt.to("The massive Titanoboa slithers silently, ready to strike.", "Titanoboa"),
            TuplesKt.to("The Trash Gobbler is hungry for you!", "Trash Gobbler"),
            TuplesKt.to("Dancing mysteriously, the Wiki Tiki shares its ancient secrets.", "Wiki Tiki"),
            TuplesKt.to("An alligator lurks in the murky waters, eyes gleaming with predatory intent.", "Alligator"),
            TuplesKt.to("Is it a frog? Is it a man? Well, yes, sorta, IT'S FROG MAN!!!!!!", "Frog Man"),
            TuplesKt.to("A Snapping Turtle is coming your way, and it's ANGRY!", "Snapping Turtle"),
            TuplesKt.to("The water bubbles and froths. A massive form emerges- you have disturbed the Wiki Tiki! You shall pay the price.", "Wiki Tiki"),
            TuplesKt.to("A leech of the mines surfaces... you've caught a Bloated Mithril Grubber.", "Bloated Mithril Grubber"),
            TuplesKt.to("A leech of the mines surfaces... you've caught a Large Mithril Grubber.", "Large Mithril Grubber"),
            TuplesKt.to("A leech of the mines surfaces... you've caught a Medium Mithril Grubber.", "Medium Mithril Grubber"),
            TuplesKt.to("A leech of the mines surfaces... you've caught a Mithril Grubber.", "Mithril Grubber"),
            TuplesKt.to("Smells of burning. Must be a Fried Chicken.", "Fried Chicken"),
            TuplesKt.to("Trouble's brewing, it's a Fireproof Witch!", "Fireproof Witch"),
            TuplesKt.to("A Fiery Scuttler inconspicuously waddles up to you, friends in tow.", "Fiery Scuttler"),
            TuplesKt.to("The sky darkens and the air thickens. The end times are upon us: Ragnarok is here.", "Ragnarok"),
            TuplesKt.to("The Loch Emperor arises from the depths.", "Loch Emperor"),
            TuplesKt.to("You've hooked an Ent, as ancient as the forest itself.", "Ent"),
            TuplesKt.to("A gang of Liltads!", "Tadgang"),
            TuplesKt.to("Look! A Wetwing emerges!", "Wetwing"),
            TuplesKt.to("You've hooked a Bogged!", "Bogged")
         )
      )
   }
